### ISSUE TITLE
Ignore decorator vulture

### ISSUE THREAD

**Issue by justuskilianwolff** [justuskilianwolff/python-template#1]
Add vulture decorator:

```toml
[tool.vulture]
exclude = [".venv", "tests"]
ignore_decorators = ["@vulture_ignore"]
```

```python
def vulture_ignore(obj):
    """Decorator to ignore vulture warnings for a function."""
    return obj
```
